### PR TITLE
fix: Fix path in README

### PR DESCRIPTION
**Pull request by tachikoma-li**
Use correct path to license in README

### CODE REVIEW

**Review by leoadec — COMMENTED** [review]
Thanks for this. Just an extra request: I think the link to the "Jupyter notebooks" in the "Usage" section might also need to be updated.

**Comment by tachikoma-li** [comment]
> Thanks for this. Just an extra request: I think the link to the "Jupyter notebooks" in the "Usage" section might also need to be updated.

Good catch. Should be fixed now.

**Review by leoadec — APPROVED** [review]
Perfect

**Comment by charmasaur** [comment]
Thanks Li!

**Pull request merged**
