### PR TITLE
Change varibale name using Q-CTRL standard

### PR DESCRIPTION
**Pull request by tachikoma-li**
`number_of_offsets` -> `offset_count`
`number_inner_offsets` -> `inner_offset_count`
`number_outer_offsets` -> `outer_offset_count`
This is a breaking change. We might do a release later after removing the drive control wrapper function.

Also removed unnecessary default values in private functions.

### CODE REVIEW

**Review by charmasaur — APPROVED** [review]
Are these parameters used in any of the notebooks in the `notebooks` repo?

**Comment by tachikoma-li** [comment]
> Are these parameters used in any of the notebooks in the `notebooks` repo?



> Are these parameters used in any of the notebooks in the `notebooks` repo?

I made changes only to the dynamical decoupling module and to my knowledge, they are not used in the the notebook repo.

**Comment by charmasaur** [comment]
Cool, sounds good. As you say, let's just make sure the next release is a major one. If you've got any other breaking changes lined up then let's get those in too.

**Comment by tachikoma-li** [comment]
> Cool, sounds good. As you say, let's just make sure the next release is a major one. If you've got any other breaking changes lined up then let's get those in too.

yep, that's the plan. I'll hold the relase unitl we finish fixing the drive control.

**Review by charmasaur — APPROVED** [review]

**Pull request merged**
