### PR TITLE
Update docs and licence info 

### PR DESCRIPTION
**Pull request by saltysealion**
Fixes https://q-ctrl.atlassian.net/browse/DEVOPS-263

### CODE REVIEW

**Comment by stevegore** [comment]
Thanks for this. Think you may still need to remove License from https://github.com/qctrl/python-open-controls/blob/DEVOPS-263/docs/index.rst ?

**Comment by saltysealion** [comment]
Thanks @stevegore. By the way, 
WIP stands for work in progresss. I wouldn’t want you to spend more time on this when there are still a number of changes planned. If you really like, I can assign you to be a reviewer since this was originally a dev ops ticket? Let me know.

**Comment by michaelhush** [comment]
LGTM

The package could do with a brief description at the top of the documentation. But I'll make a task to add that after.

**Comment by stevegore** [comment]
Sorry did not notice the WIP tag. FYI you can use GitHub's draft PR feature for this so that PR's can't be ready until explicitly marked as ready for review.

**Pull request merged**
