### PR TITLE
misc: Add check for PR names

### PR DESCRIPTION
**Pull request by tachikoma-li**
To ensure we have consistent PR names as discussed in #179

### CODE REVIEW

**Review by leoadec — APPROVED** [review]
I'm okay with this, but I'll let @cfarrend decide on the strategy he prefers for adopting gitlint across the repos.

**Comment by tachikoma-li** [comment]
> I'm okay with this, but I'll let @cfarrend decide on the strategy he prefers for adopting gitlint across the repos.

ah, true, I forgot that part. If there is already a plan about applying `gitlint` across all repos, I am happy to close the PR.

**Comment by leoadec** [comment]
@tachikoma-li I'm not sure if we already have a plan, but devops have been thinking about it, so they might be the best to advise on which approach will be easier to maintain in the future.

**Comment by tachikoma-li** [comment]
> @tachikoma-li I'm not sure if we already have a plan, but devops have been thinking about it, so they might be the best to advise on which approach will be easier to maintain in the future.

I guess I'll merge this one for now. We can revise it once dev has a better way to consistently manage this issue across repos.

**Pull request merged**
