### PR TITLE
Migrate notebooks.

### PR DESCRIPTION
**Pull request by michaelhush**
Notebooks have been migrated to https://github.com/qctrl/notebooks/tree/master/qctrl-open-controls and readme has been updated accordingly.

### CODE REVIEW

**Comment by michaelhush** [comment]
@stevegore the notebooks were previously automatically checked in the testing. They have been migrated, so could you please remove them from the circleCI automated tests.

**Comment by stevegore** [comment]
Hey all, the builds will automatically add ```--nbval-lax``` to ```pytest``` if it detects *.ipynb files. You will need to remove the ```nbval``` dependency though. 

I'm going to put some documentation on how to do this sort of thing, but for the moment:

1. Install Poetry if you haven't got it:
```bash
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
```
2. Remove the dependency:
```bash
poetry remove --dev nbval
``` 
Happy to walk through with you guys in more detail via chat if you'd rather.

**Comment by stevegore** [comment]
Actually, just realised your branch has the old workflow. I'll need to get my PR merged, then you can get merge in those chances into this PR, then the above applies.

After I have the release done I'll ensure that happens.

**Comment by stevegore** [comment]
@rajibchakravorty @michaelhush I've done this for you for this PR. Going to merge. Still having issues with it expecting a check that doesn't exist.

**Pull request merged**
