### PR TITLE
fix: Fix doc typos in driven_controls/predefined.py

### PR DESCRIPTION
**Pull request by FlorianH-1QBit**
The expressions for the CORPSE angle $\theta^3$ in the doc strings of `new_corpse_control`, and the three methods `new_corpse_in_*_control`, were missing a $\sin^{-1}$. This PR adds the sin^{-1} in four places. The code itself looks correct.

### CODE REVIEW

**Comment by tachikoma-li** [comment]
Hi @FlorianH-1QBit, thanks for the PR! There was an issue in our PR workflow and should be fixed now. Can you merge the change to your branch, then the CI issue would be resolved.

**Comment by FlorianH-1QBit** [comment]
I've merged the change into my branch!

**Comment by tachikoma-li** [comment]
> I've merged the change into my branch!

Hi @FlorianH-1QBit, there was another CI issue on our end and should be fixed now. Sorry about that. Thanks again for your contribution!

**Review by tachikoma-li — APPROVED** [review]
Thanks @FlorianH-1QBit !
🎉

**Pull request merged**
