### PR TITLE
Fixing CORPSE typo

### PR DESCRIPTION
**Pull request by leoadec**
Just a small fix for a typo that's been around since the beginning of time

### CODE REVIEW

**Comment by tachikoma-li** [comment]
Hopefully, we can get rid of these strings later.

**Comment by leoadec** [comment]
@charmasaur @cfarrend I just merged this before I had approval from anybody from the support group (which I think are the code owners). I suspect this isn't something I should be allowed to do?

**Comment by charmasaur** [comment]
Indeed, I wouldn't expect that to be allowed either. I guess this is the same thing we saw for the schemas in api2. Hopefully Chris can shed some light on it.

**Comment by charmasaur** [comment]
https://docs.github.com/en/github/administering-a-repository/enabling-required-reviews-for-pull-requests suggests it's just a setting we can configure. IMO it should be turned on.

**Comment by cfarrend** [comment]
Yep, it's a setting we can turn on and apply to our standards. I think it should be fine to apply across the board, I will just have a look if it conflicts with auto commits such as [this one](https://github.com/qctrl/python-open-controls/commit/b11193958a9b32c625224a93aac6220b0415474f)

**Pull request merged**
