### PR TITLE
misc: Add pre-commit hooks

### PR DESCRIPTION
**Pull request by leoadec**
This pull request adds the pre-commit hooks to Open Controls. These are optional, but can be used to check whether the files modified by a commit conform to the linting rules of the repository.

### CODE REVIEW

**Review by charmasaur — DISMISSED** [review]
Is the plan to update the CI to use the pre-commit hook in a subsequent PR?

**Review by tachikoma-li — DISMISSED** [review]
Looks good. Thanks for doing it.
Have the same question as Harry mentioned.

**Comment by leoadec** [comment]
Yes, I was planning to do that in a separate pull request to avoid having to bother devops already, but now I realize that the workflow files were changed anyway by the hooks, so I might as well update them here.

**Review by charmasaur — APPROVED** [review]

**Review by tachikoma-li — APPROVED** [review]

**Review by cfarrend — APPROVED** [review]
Looks good to me!

**Pull request merged**
