### PR TITLE
Removing setup-poetry.sh

### PR DESCRIPTION
**Pull request by leoadec**
Currently the `poetry-setup.py` script only detects an installation of poetry if it is in version 0.12.x. However, poetry has been in version 1.x for a while now. This pull request updates the script accordingly.

### CODE REVIEW

**Review by charmasaur — APPROVED** [review]

**Review by cfarrend — COMMENTED** [review]
Is anyone making use of this script? @qctrl/devops-engineering aren't using it so it can be deleted if no one else is

**Comment by leoadec** [comment]
@cfarrend I think the only reason why this script still exists is because it is mentioned in the README  as part of the installation instructions (https://github.com/qctrl/python-open-controls#from-source). That said, I'd be happy to just update the README and delete the script

**Comment by cfarrend** [comment]
This script may have been created when Poetry was still in its infancy. I think referring to the official installation instructions will be more useful https://python-poetry.org/docs/#installation as it contains instructions Linux, OSX and Windows

So yeah I'd say removing the script and suggesting the official install docs may be better for collaborators

**Comment by leoadec** [comment]
Sounds good, I've removed the file and removed the mentions of it from the documentation.

**Review by charmasaur — APPROVED** [review]

**Review by cfarrend — APPROVED** [review]

**Pull request merged**
